### ISSUE TITLE
Add GameBoy screen

### ISSUE THREAD

**Issue by d4ilyrun** [d4ilyrun/emu-gb#19]
## Description

What is the point of an emulator if we cannot see the game?

The GameBoy uses a dedicated PPU to process pixels on screen which uses FIFO mechanism through pixel fetchers in order to udpate the pixels during frames.

## Documentation

- [Pan docs](https://gbdev.io/pandocs/Rendering.html): Not very well detailed on the pixel fetcher part
- [The ultimate GameBoy talk](https://youtu.be/HyzD8pNlpwI?t=1750): The Bible. 
- [Blog](https://blog.tigris.fr/2019/09/15/writing-an-emulator-the-first-pixel): Focused on the pixel fetcher

## TODO

- [x] Add support for the GameBoy LCD screen
	- [x] Registers
	- [x] R/W operations
	- [x] Dedicated memory
- [ ] Graphical interface
	- [ ] A simple GUI
	- [ ] Debug mode (see video memory content, etc ...)
- [ ] PPU
	- [ ] Timing
	- [ ] Pixel fetcher
	- [ ] Send pixel to the screen

## Testing

Testing this part is _**REQUIRED**_.
No related PR will be approved without tests.
